# Generated by Django 3.0.4 on 2021-02-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20210212_1149'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Санвузол'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Кімнат'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default='House', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='open_house',
            field=models.BooleanField(default=False, verbose_name='Відкритий'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor', verbose_name='Имя риелтова'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('Продаж', 'For Sale'), ('Аренда', 'For Rent')], default='Продаж', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(verbose_name='Мін ціна'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=15, verbose_name='Код'),
        ),
    ]
